../fastSemSim.sh --o_type DiseaseOntology -a ./data/ACs/DO_human_ac_plain.txt --ac_type plain --tss SimICND --tmix BMA --query_ss_type obj --query_type SS --query_input file --query_file  ./data/query/DO_list_objset_query.txt --query_mode list -v 
../fastSemSim.sh --o_type DiseaseOntology -a ./data/ACs/DO_human_ac_plain.txt --ac_type plain --tss SimICND --tmix BMA --query_ss_type objset --query_type SS --query_input file --query_file  ./data/query/DO_list_objset_query.txt --query_mode list -v 
../fastSemSim.sh --o_type DiseaseOntology -a ./data/ACs/DO_human_ac_plain.txt --ac_type plain --tss SimICND --tmix BMA --query_ss_type term --query_type SS --query_input file --query_file  ./data/query/DO_list_objset_query.txt --query_mode list -v 
../fastSemSim.sh --o_type DiseaseOntology -a ./data/ACs/DO_human_ac_plain.txt --ac_type plain --tss SimICND --tmix BMA --query_ss_type termset --query_type SS --query_input file --query_file  ./data/query/DO_list_objset_query.txt --query_mode list -v 
../fastSemSim.sh   --tss SimICND --tmix BMA --query_ss_type obj --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh   --tss SimICND --tmix BMA --query_ss_type objset --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh   --tss SimICND --tmix BMA --query_ss_type term --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh   --tss SimICND --tmix BMA --query_ss_type termset --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh  -a ./data/ACs/gene_association.goa_fly --ac_type gaf2 --tss SimICND --tmix BMA --query_ss_type obj --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh  -a ./data/ACs/gene_association.goa_fly --ac_type gaf2 --tss SimICND --tmix BMA --query_ss_type objset --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh  -a ./data/ACs/gene_association.goa_fly --ac_type gaf2 --tss SimICND --tmix BMA --query_ss_type term --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh  -a ./data/ACs/gene_association.goa_fly --ac_type gaf2 --tss SimICND --tmix BMA --query_ss_type termset --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type GeneOntology -o ./data/Os/GeneOntology_full_2013.09.10.obo --o_file_format obo  --tss SimICND --tmix BMA --query_ss_type obj --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type GeneOntology -o ./data/Os/GeneOntology_full_2013.09.10.obo --o_file_format obo  --tss SimICND --tmix BMA --query_ss_type objset --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type GeneOntology -o ./data/Os/GeneOntology_full_2013.09.10.obo --o_file_format obo  --tss SimICND --tmix BMA --query_ss_type term --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type GeneOntology -o ./data/Os/GeneOntology_full_2013.09.10.obo --o_file_format obo  --tss SimICND --tmix BMA --query_ss_type termset --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type GeneOntology -o ./data/Os/GeneOntology_full_2013.09.10.obo --o_file_format obo -a ./data/ACs/gene_association.goa_fly --ac_type gaf2 --tss SimICND --tmix BMA --query_ss_type obj --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type GeneOntology -o ./data/Os/GeneOntology_full_2013.09.10.obo --o_file_format obo -a ./data/ACs/gene_association.goa_fly --ac_type gaf2 --tss SimICND --tmix BMA --query_ss_type objset --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type GeneOntology -o ./data/Os/GeneOntology_full_2013.09.10.obo --o_file_format obo -a ./data/ACs/gene_association.goa_fly --ac_type gaf2 --tss SimICND --tmix BMA --query_ss_type term --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type GeneOntology -o ./data/Os/GeneOntology_full_2013.09.10.obo --o_file_format obo -a ./data/ACs/gene_association.goa_fly --ac_type gaf2 --tss SimICND --tmix BMA --query_ss_type termset --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type Ontology  --tss SimICND --tmix BMA --query_ss_type obj --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type Ontology  --tss SimICND --tmix BMA --query_ss_type objset --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type Ontology  --tss SimICND --tmix BMA --query_ss_type term --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type Ontology  --tss SimICND --tmix BMA --query_ss_type termset --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type Ontology -a ./data/ACs/gene_association.goa_fly --ac_type gaf2 --tss SimICND --tmix BMA --query_ss_type obj --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type Ontology -a ./data/ACs/gene_association.goa_fly --ac_type gaf2 --tss SimICND --tmix BMA --query_ss_type objset --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type Ontology -a ./data/ACs/gene_association.goa_fly --ac_type gaf2 --tss SimICND --tmix BMA --query_ss_type term --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type Ontology -a ./data/ACs/gene_association.goa_fly --ac_type gaf2 --tss SimICND --tmix BMA --query_ss_type termset --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type GeneOntology -o ./data/Os/GeneOntology_filtered_2013.09.10.obo-xml.gz --o_file_format obo-xml  --tss SimICND --tmix BMA --query_ss_type obj --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type GeneOntology -o ./data/Os/GeneOntology_filtered_2013.09.10.obo-xml.gz --o_file_format obo-xml  --tss SimICND --tmix BMA --query_ss_type objset --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type GeneOntology -o ./data/Os/GeneOntology_filtered_2013.09.10.obo-xml.gz --o_file_format obo-xml  --tss SimICND --tmix BMA --query_ss_type term --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type GeneOntology -o ./data/Os/GeneOntology_filtered_2013.09.10.obo-xml.gz --o_file_format obo-xml  --tss SimICND --tmix BMA --query_ss_type termset --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type GeneOntology -o ./data/Os/GeneOntology_filtered_2013.09.10.obo-xml.gz --o_file_format obo-xml -a ./data/ACs/gene_association.goa_fly --ac_type gaf2 --tss SimICND --tmix BMA --query_ss_type obj --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type GeneOntology -o ./data/Os/GeneOntology_filtered_2013.09.10.obo-xml.gz --o_file_format obo-xml -a ./data/ACs/gene_association.goa_fly --ac_type gaf2 --tss SimICND --tmix BMA --query_ss_type objset --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type GeneOntology -o ./data/Os/GeneOntology_filtered_2013.09.10.obo-xml.gz --o_file_format obo-xml -a ./data/ACs/gene_association.goa_fly --ac_type gaf2 --tss SimICND --tmix BMA --query_ss_type term --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type GeneOntology -o ./data/Os/GeneOntology_filtered_2013.09.10.obo-xml.gz --o_file_format obo-xml -a ./data/ACs/gene_association.goa_fly --ac_type gaf2 --tss SimICND --tmix BMA --query_ss_type termset --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type GeneOntology  --tss SimICND --tmix BMA --query_ss_type obj --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type GeneOntology  --tss SimICND --tmix BMA --query_ss_type objset --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type GeneOntology  --tss SimICND --tmix BMA --query_ss_type term --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type GeneOntology  --tss SimICND --tmix BMA --query_ss_type termset --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type GeneOntology -a ./data/ACs/gene_association.goa_fly --ac_type gaf2 --tss SimICND --tmix BMA --query_ss_type obj --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type GeneOntology -a ./data/ACs/gene_association.goa_fly --ac_type gaf2 --tss SimICND --tmix BMA --query_ss_type objset --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type GeneOntology -a ./data/ACs/gene_association.goa_fly --ac_type gaf2 --tss SimICND --tmix BMA --query_ss_type term --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type GeneOntology -a ./data/ACs/gene_association.goa_fly --ac_type gaf2 --tss SimICND --tmix BMA --query_ss_type termset --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type Ontology -o ./data/Os/GeneOntology_filtered_2013.09.10.obo-xml.gz --o_file_format obo-xml  --tss SimICND --tmix BMA --query_ss_type obj --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type Ontology -o ./data/Os/GeneOntology_filtered_2013.09.10.obo-xml.gz --o_file_format obo-xml  --tss SimICND --tmix BMA --query_ss_type objset --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type Ontology -o ./data/Os/GeneOntology_filtered_2013.09.10.obo-xml.gz --o_file_format obo-xml  --tss SimICND --tmix BMA --query_ss_type term --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type Ontology -o ./data/Os/GeneOntology_filtered_2013.09.10.obo-xml.gz --o_file_format obo-xml  --tss SimICND --tmix BMA --query_ss_type termset --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type Ontology -o ./data/Os/GeneOntology_filtered_2013.09.10.obo-xml.gz --o_file_format obo-xml -a ./data/ACs/gene_association.goa_fly --ac_type gaf2 --tss SimICND --tmix BMA --query_ss_type obj --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type Ontology -o ./data/Os/GeneOntology_filtered_2013.09.10.obo-xml.gz --o_file_format obo-xml -a ./data/ACs/gene_association.goa_fly --ac_type gaf2 --tss SimICND --tmix BMA --query_ss_type objset --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type Ontology -o ./data/Os/GeneOntology_filtered_2013.09.10.obo-xml.gz --o_file_format obo-xml -a ./data/ACs/gene_association.goa_fly --ac_type gaf2 --tss SimICND --tmix BMA --query_ss_type term --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
../fastSemSim.sh --o_type Ontology -o ./data/Os/GeneOntology_filtered_2013.09.10.obo-xml.gz --o_file_format obo-xml -a ./data/ACs/gene_association.goa_fly --ac_type gaf2 --tss SimICND --tmix BMA --query_ss_type termset --query_type SS --query_input file --query_file  ./data/query/GO_fly_list_query.txt --query_mode list -v 
